# Site settings
baseurl = ""
languageCode = "en-US"


canonifyurls = false

author = "Andrew Samoil"
title = "Andrew Samoil"

contentdir = "content"
layoutdir = "layouts"
publishdir = "docs"


# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Copyright
copyright = "&copy; 2021 Andrew Samoil"

[params]

  # Metadata for search engines and social sharing
  author = "Andrew Samoil"
  keywords = "Andrew Samoil"

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/joe.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Connect"

      [[params.links.list1.link]]
        text = "Email"
        url = "mailto:aisamoil@ualberta.ca"

      [[params.links.list1.link]]
        text = "LinkedIn"
        url = "https://www.linkedin.com/in/andrew-samoil/"

      [[params.links.list1.link]]
        text = "Resume"
        url = "images/resume.pdf"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Social"

      [[params.links.list2.link]]
        text = "Instagram"
        url = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"

      [[params.links.list2.link]]
        text = "Youtube"
        url = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"

      [[params.links.list2.link]]
        text = ""
        url = "#"

  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Network"

      [[params.links.list3.link]]
        text = "Github"
        url = "https://github.com/Andy419"

      [[params.links.list3.link]]
        text = ""
        url = "#"

      [[params.links.list3.link]]
        text = ""
        url = "#"
